import cv2
import matplotlib.pyplot as plt
import numpy as np
img=cv2.imread(r"E:\Hons 3rd Year 2nd semester books\Digital Image Processing\DIP Lab\fb profile small.jpg",0)
img= cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
R,G,B=img[:,:,0],img[:,:,1],img[:,:,2]
plt.figure(figsize=(10,4))
plt.subplot(1,3,1)
plt.imshow(R,cmap='gray')
plt.title("Red Channel")
plt.axis('off')
plt.subplot(1,3,2)
plt.imshow(G,cmap='gray')
plt.title("Green Channel")
plt.axis('off')
plt.subplot(1,3,3)
plt.imshow(B,cmap='gray')
plt.title("Blue Channnel")
plt.axis('off')
plt.show()
plt.figure(figsize=(12,8))
plt.subplot(2,3,1)
plt.imshow(img,cmap='gray')
plt.title("Orginal image")
plt.axis('off')
negetive=255-img
plt.subplot(2,3,2)
plt.imshow(negetive,cmap='gray')
plt.title("Negetive Image")
plt.axis('off')
c=255/(np.log(1+np.max(img)))
logimage=c *(np.log(1+img))
logimage=np.array(logimage,dtype=np.uint8)
plt.subplot(2,3,3)
plt.imshow(logimage,cmap='gray')
plt.title("Log transformation")
plt.axis('off')
gamma=0.5
gammaimage=np.array(255*(img/255)**gamma,dtype=np.uint8)
plt.subplot(2,3,4)
plt.imshow(gammaimage,cmap='gray')
plt.title("Gamma transformation")
plt.axis('off')
rmin,rmax=np.min(img),np.max(img)
contraststrech=((img-rmin)/(rmax-rmin))*255
contraststrech=np.array(contraststrech,dtype=np.uint8)
plt.subplot(2,3,5)
plt.imshow(contraststrech,cmap='gray')
plt.title("Contrast Stratching")
plt.axis('off')
plt.tight_layout()
plt.show()
print("Original Image Size:",img.size)
print("Negetive Image Size:",negetive.size)
print("Log Transform Image Size:",logimage.size)
print("Gamma Transform Image Size:",gammaimage.size)
print("Contrast Stratching Image Size:",contraststrech.size)
print("Original Image Shape:",img.shape)
print("Negetive Image Shape:",negetive.shape)
print("Log Transform Image Shape:",logimage.shape)
print("Gamma Transform Image Shape:",gammaimage.shape)
print("Contrast Stratching Image Shape:",contraststrech.shape)
