import cv2
import matplotlib.pyplot as plt
import numpy as np
img=cv2.imread(r"E:\Hons 3rd Year 2nd semester books\Digital Image Processing\DIP Lab\fb profile small.jpg",0)
img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
plt.imshow(img,cmap='gray')
plt.title("Original Image")
plt.axis('off')
plt.show()
R,G,B=img[:,:,0],img[:,:,1],img[:,:,2]
plt.figure(figsize=(12,4))
plt.subplot(1,3,1)
plt.imshow(R,cmap='gray')
plt.title("Red Channel")
plt.axis('off')
plt.subplot(1,3,2)
plt.imshow(G,cmap='gray')
plt.title("Green Channnel")
plt.axis('off')
plt.subplot(1,3,2)
plt.imshow(B,cmap='gray')
plt.title("Blue Channnel")
plt.axis('off')
plt.show()
print("Original Image Size:",img.size)
print("Original Image Shape",img.shape)
laplacian=cv2.Laplacian(img,cv2.CV_64F)
laplacian=np.uint8(np.absolute(laplacian))
plt.imshow(laplacian,cmap='gray')
plt.title("Laplacian Image")
plt.axis('off')
plt.show()
print("Laplacian Image Size",laplacian.size)
print("Laplacian Image Shape",laplacian.shape)
sharped=cv2.add(img,laplacian)
plt.imshow(sharped,cmap='gray')
plt.title("Sharped Image")
plt.axis('off')
plt.show()
print("Sharped Image Size",sharped.size)
print("Sharped Image Shape",sharped.shape)
plt.figure(figsize=(12,4))
plt.subplot(1,3,1)
plt.title("Original Image")
plt.imshow(img)
plt.axis('off')
plt.subplot(1,3,2)
plt.title("Laplacian Image")
plt.imshow(laplacian)
plt.axis('off')
plt.subplot(1,3,3)
plt.title("Sharped Image")
plt.imshow(sharped)
plt.axis('off')
plt.show()
